---
defaults:
  memory: 1024
  cpus: 1
  domain: 'local'
  network_prefix: '172.22.3'
  synced_folder_type: 'sshfs'
  puppet_agent_version: '5.5.4' # Supports Puppet version from 4 to 6
nodes:
  puppet:
    memory: 2048
    cpus: 2
    box: centos/7
  centos-7:
    box: centos/7
  # centos-6:
  #   box: centos/6
  # centos-5:
  #   box: gutocarvalho/centos5x64nocm
  # ubuntu-18.04:
  #   box: ubuntu/bionic64
  # ubuntu-16.04:
  #   box: ubuntu/xenial64
  # ubuntu-14.04:
  #   box: ubuntu/trusty64
  # ubuntu-12.04:
  #   box: ubuntu/precise64
  #   puppet_agent_version: '1.10.0' # Latest release
  # debian-9:
  #   box: debian/stretch64
  # debian-8:
  #   box: debian/jessie64
  # debian-7:
  #   box: debian/wheezy64
  #   puppet_agent_version: '5.5.1' # Latest release
  # debian-6:
  #   box: gutocarvalho/debian6x64nocm
  #   puppet_agent_version: '1.4.1' # Latest release
  # sles-11:
  #   box: elastic/sles-11-x86_64
  # sles-12:
  #   box: elastic/sles-12-x86_64
  # windows-2012:
  #   memory: 2048
  #   cpus: 2
  #   type: windows
  #   box: opentable/win-2012r2-standard-amd64-nocm
  # windows-2008:
  #   memory: 2048
  #   cpus: 2
  #   type: windows
  #   box: opentable/win-2008r2-standard-amd64-nocm
  # oracle-7:
  #   box: oracle/7
  #   box_url: https://yum.oracle.com/boxes/oraclelinux/ol75/ol75.box
  # oracle-6:
  #   box: oracle/6
  #   box_url: https://yum.oracle.com/boxes/oraclelinux/ol610/ol610.box
  # oracle-5:
  #   box: gutocarvalho/oracle5x64nocm
  # windows-2016:
  #   memory: 2048
  #   cpus: 2
  #   type: windows
  #   box: mwrock/Windows2016
